import type { Property } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const properties: Property[] = [
  {
    id: '1',
    ownerId: 'user-1',
    ownerName: 'Jane Doe',
    title: 'Modern Family Home in Suburbia',
    listingFor: 'Sale',
    propertyType: 'House',
    price: 4500000,
    areaSqFt: 2200,
    address: '123 Maple Street',
    city: 'Springfield',
    pincode: '12345',
    description: 'A beautiful and spacious modern family home located in a quiet suburban neighborhood. Perfect for families, with a large backyard and close to top-rated schools.',
    photos: [
      getImage('property-1-exterior'),
      getImage('property-1-living'),
      getImage('property-1-kitchen'),
    ],
    amenities: ['Backyard', 'Garage', 'Modern Kitchen', 'Air Conditioning', 'Bore Water'],
    nearbyPlaces: [
      { name: 'Springfield Elementary', distance: '0.5 miles' },
      { name: 'City Hospital', distance: '2 miles' },
      { name: 'Central Park', distance: '1 mile' },
    ],
    beds: 4,
    baths: 3,
    bhk: '4BHK',
    furnishing: 'Semi-furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-20T10:00:00Z',
    postedByType: 'Owner',
    isApproved: true,
    postedAt: new Date(),
    updatedAt: new Date(),
    isNew: true,
  },
  {
    id: '2',
    ownerId: 'user-2',
    ownerName: 'John Smith',
    title: 'Cozy Downtown Apartment',
    listingFor: 'Rent',
    propertyType: 'Flat',
    price: 22000,
    areaSqFt: 950,
    address: '456 Oak Avenue, Apt 5B',
    city: 'Metropolis',
    pincode: '54321',
    description: 'A stylish and cozy apartment in the heart of downtown. Features stunning city views and is within walking distance of shops, restaurants, and public transport.',
    photos: [
      getImage('property-2-exterior'),
      getImage('property-2-bedroom'),
    ],
    amenities: ['City View', 'Gym Access', '24/7 Security', 'Elevator', 'Parking'],
    nearbyPlaces: [
      { name: 'Metro Station', distance: '0.2 miles' },
      { name: 'Downtown Mall', distance: '0.1 miles' },
    ],
    beds: 2,
    baths: 2,
    bhk: '2BHK',
    furnishing: 'Furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-22T14:30:00Z',
    postedByType: 'Agent',
    isApproved: true,
    postedAt: new Date(),
    updatedAt: new Date(),
    isUrgent: true,
  },
  {
    id: '3',
    ownerId: 'user-3',
    ownerName: 'Prestige Properties',
    title: 'Luxury Villa with Private Pool',
    listingFor: 'Sale',
    propertyType: 'House',
    price: 12000000,
    areaSqFt: 4500,
    address: '789 Pine Lane',
    city: 'Beverly Hills',
    pincode: '90210',
    description: 'An exquisite luxury villa offering unparalleled comfort and privacy. Boasts a private swimming pool, home theater, and beautifully landscaped gardens.',
    photos: [
      getImage('property-3-exterior'),
    ],
    amenities: ['Private Pool', 'Home Theater', 'Landscaped Garden', 'Gated Community', 'Parking'],
    nearbyPlaces: [
      { name: 'Rodeo Drive', distance: '3 miles' },
    ],
    beds: 5,
    baths: 6,
    bhk: '5BHK',
    furnishing: 'Furnished',
    featured: false,
    listingStatus: 'approved',
    dateAdded: '2024-07-18T09:00:00Z',
    postedByType: 'Builder',
    isApproved: true,
    postedAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    ownerId: 'user-4',
    ownerName: 'Corporate Realty',
    title: 'Spacious Commercial Office Space',
    listingFor: 'Lease',
    propertyType: 'Commercial',
    price: 50000,
    areaSqFt: 3000,
    address: '101 Business Boulevard',
    city: 'Metropolis',
    pincode: '54322',
    description: 'Prime commercial office space in a high-traffic business district. Open floor plan, modern amenities, and ample parking. Ideal for startups and established businesses.',
    photos: [
      getImage('property-5-exterior'),
    ],
    amenities: ['Ample Parking', 'Conference Rooms', 'High-Speed Internet', 'Reception Area'],
    nearbyPlaces: [
      { name: 'City Convention Center', distance: '1 mile' },
    ],
    beds: 0,
    baths: 4,
    furnishing: 'Unfurnished',
    featured: false,
    listingStatus: 'pending',
    dateAdded: '2024-07-23T11:00:00Z',
    postedByType: 'Agent',
    isApproved: false,
    postedAt: new Date(),
    updatedAt: new Date(),
    isNew: true,
  },
    {
    id: '5',
    ownerId: 'user-5',
    ownerName: 'Emily White',
    title: 'Charming Suburban Home',
    listingFor: 'Sale',
    propertyType: 'House',
    price: 3750000,
    areaSqFt: 1800,
    address: '246 Birch Road',
    city: 'Springfield',
    pincode: '12345',
    description: 'A delightful suburban home with a picket fence and a lovely garden. Perfect for starting a family. Recently renovated kitchen.',
    photos: [
        getImage('property-2-exterior'),
    ],
    amenities: ['Garden', 'Renovated Kitchen', 'Fireplace', 'Parking', 'Bore Water'],
    nearbyPlaces: [
        { name: 'Springfield High', distance: '1.5 miles' },
        { name: 'Community Pool', distance: '0.8 miles' },
    ],
    beds: 3,
    baths: 2,
    bhk: '3BHK',
    furnishing: 'Semi-furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-24T18:00:00Z',
    postedByType: 'Owner',
    isApproved: true,
    postedAt: new Date(),
    updatedAt: new Date(),
    isUrgent: true,
  },
];
