import type { Property, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Family Home in Suburbia',
    status: 'For Sale',
    type: 'House',
    price: 4500000,
    areaSqFt: 2200,
    address: '123 Maple Street',
    city: 'Springfield',
    pincode: '12345',
    description: 'A beautiful and spacious modern family home located in a quiet suburban neighborhood. Perfect for families, with a large backyard and close to top-rated schools.',
    photos: [
      getImage('property-1-exterior'),
      getImage('property-1-living'),
      getImage('property-1-kitchen'),
    ],
    owner: {
      name: 'Jane Doe',
      phone: '555-123-4567',
      isAgent: false,
      verified: true,
    },
    amenities: ['Backyard', 'Garage', 'Modern Kitchen', 'Air Conditioning', 'Bore Water'],
    nearbyPlaces: [
      { name: 'Springfield Elementary', distance: '0.5 miles' },
      { name: 'City Hospital', distance: '2 miles' },
      { name: 'Central Park', distance: '1 mile' },
    ],
    beds: 4,
    baths: 3,
    bhk: '4BHK',
    furnishing: 'Semi-furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-20T10:00:00Z',
    isNew: true,
  },
  {
    id: '2',
    title: 'Cozy Downtown Apartment',
    status: 'For Rent',
    type: 'Flat',
    price: 22000,
    areaSqFt: 950,
    address: '456 Oak Avenue, Apt 5B',
    city: 'Metropolis',
    pincode: '54321',
    description: 'A stylish and cozy apartment in the heart of downtown. Features stunning city views and is within walking distance of shops, restaurants, and public transport.',
    photos: [
      getImage('property-2-exterior'),
      getImage('property-2-bedroom'),
    ],
    owner: {
      name: 'John Smith',
      phone: '555-987-6543',
      isAgent: true,
      verified: true,
    },
    amenities: ['City View', 'Gym Access', '24/7 Security', 'Elevator', 'Parking'],
    nearbyPlaces: [
      { name: 'Metro Station', distance: '0.2 miles' },
      { name: 'Downtown Mall', distance: '0.1 miles' },
    ],
    beds: 2,
    baths: 2,
    bhk: '2BHK',
    furnishing: 'Furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-22T14:30:00Z',
    isUrgent: true,
  },
  {
    id: '3',
    title: 'Luxury Villa with Private Pool',
    status: 'For Sale',
    type: 'House',
    price: 12000000,
    areaSqFt: 4500,
    address: '789 Pine Lane',
    city: 'Beverly Hills',
    pincode: '90210',
    description: 'An exquisite luxury villa offering unparalleled comfort and privacy. Boasts a private swimming pool, home theater, and beautifully landscaped gardens.',
    photos: [
      getImage('property-3-exterior'),
    ],
    owner: {
      name: 'Prestige Properties',
      phone: '555-111-2222',
      isAgent: true,
      verified: false,
    },
    amenities: ['Private Pool', 'Home Theater', 'Landscaped Garden', 'Gated Community', 'Parking'],
    nearbyPlaces: [
      { name: 'Rodeo Drive', distance: '3 miles' },
    ],
    beds: 5,
    baths: 6,
    bhk: '5BHK',
    furnishing: 'Furnished',
    featured: false,
    listingStatus: 'approved',
    dateAdded: '2024-07-18T09:00:00Z',
  },
  {
    id: '4',
    title: 'Spacious Commercial Office Space',
    status: 'For Lease',
    type: 'Commercial',
    price: 50000,
    areaSqFt: 3000,
    address: '101 Business Boulevard',
    city: 'Metropolis',
    pincode: '54322',
    description: 'Prime commercial office space in a high-traffic business district. Open floor plan, modern amenities, and ample parking. Ideal for startups and established businesses.',
    photos: [
      getImage('property-5-exterior'),
    ],
    owner: {
      name: 'Corporate Realty',
      phone: '555-333-4444',
      isAgent: true,
      verified: true,
    },
    amenities: ['Ample Parking', 'Conference Rooms', 'High-Speed Internet', 'Reception Area'],
    nearbyPlaces: [
      { name: 'City Convention Center', distance: '1 mile' },
    ],
    beds: 0,
    baths: 4,
    furnishing: 'Unfurnished',
    featured: false,
    listingStatus: 'pending',
    dateAdded: '2024-07-23T11:00:00Z',
    isNew: true,
  },
    {
    id: '5',
    title: 'Charming Suburban Home',
    status: 'For Sale',
    type: 'House',
    price: 3750000,
    areaSqFt: 1800,
    address: '246 Birch Road',
    city: 'Springfield',
    pincode: '12345',
    description: 'A delightful suburban home with a picket fence and a lovely garden. Perfect for starting a family. Recently renovated kitchen.',
    photos: [
        getImage('property-2-exterior'),
    ],
    owner: {
        name: 'Emily White',
        phone: '555-222-3333',
        isAgent: false,
        verified: true,
    },
    amenities: ['Garden', 'Renovated Kitchen', 'Fireplace', 'Parking', 'Bore Water'],
    nearbyPlaces: [
        { name: 'Springfield High', distance: '1.5 miles' },
        { name: 'Community Pool', distance: '0.8 miles' },
    ],
    beds: 3,
    baths: 2,
    bhk: '3BHK',
    furnishing: 'Semi-furnished',
    featured: true,
    listingStatus: 'approved',
    dateAdded: '2024-07-24T18:00:00Z',
    isUrgent: true,
  },
];


export const users: User[] = [
  {
    id: 'user-1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    phone: '555-123-4567',
    dateJoined: '2024-06-15T10:00:00Z',
    role: 'Owner',
    listings: 1,
  },
  {
    id: 'user-2',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '555-987-6543',
    dateJoined: '2024-06-20T11:30:00Z',
    role: 'Agent',
    listings: 3,
  },
  {
    id: 'user-3',
    name: 'Prestige Properties',
    email: 'contact@prestigeproperties.com',
    phone: '555-111-2222',
    dateJoined: '2024-05-10T09:00:00Z',
    role: 'Builder',
    listings: 5,
  },
  {
    id: 'user-4',
    name: 'Corporate Realty',
    email: 'info@corporaterealty.com',
    phone: '555-333-4444',
    dateJoined: '2024-07-01T14:00:00Z',
    role: 'Agent',
    listings: 10,
  },
  {
    id: 'user-5',
    name: 'Emily White',
    email: 'emily.white@example.com',
    phone: '555-222-3333',
    dateJoined: '2024-07-10T18:00:00Z',
    role: 'Owner',
    listings: 2,
  }
];
